# NOTE: This compose file is draft
services:
  angular-front:
    build:
      dockerfile: Dockerfile
    volumes:
      - ../../angular-front:/workspace:cached
  nest-api:
    build:
      dockerfile: ../nest-api/Dockerfile
    volumes:
      - ../../nest-api:/workspace:cached
    command: >
      sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
